### ISSUE TITLE
auto-redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by gabor** [ufx/GarlandTools#17]
hi,

both http://garlandtools.org/db/ and https://garlandtools.org/db/ work. could the HTTP version redirect to the HTTPS version automatically?

**Comment by ufx** [comment]
There is a hidden setting that will do this.  In your browser's Javascript console, write:
gt.settings.data.normalizeUrl = 1;
gt.settings.saveDirty();

Be warned that it will be difficult to switch back to the http site if you did not previously synchronize your lists and other data with the server.

**Comment by gabor** [comment]
thanks for the info. if i may, is there a reason not to have this enabled by default? are there use-cases where one wants to stay on not-https?

**Comment by ufx** [comment]
The site was initially http-only until Cloudflare enabled us to go all https.  Since these are separate domains for localStorage I couldn't bring http users to the https site without losing all their data.  I later wrote server syncing to help with that, but the final piece is still missing: Automatically sync user data to temporary storage so it can be retrieved when the user is permanently on https.

**Comment by gabor** [comment]
i see,makes sense. thanks for the help.
